from OrderedEnum import OrderedEnum
from enum import Enum
from color import Color



class Mana(Enum):
    """
    Mana can be considered the objects with which (most) costs are paid, there are
    5 colors of mana, as well as colorless mana, which can be considered to have no
    color.

    Mana is generated by land, this is distinct from mana *costs* which are a specific
    subset of costs, the things that you pay to cast spells and activate abilities.
    """
    pass

class ManaSymbol(OrderedEnum):
    pass

class ManaCost():
    pass